name: Build
on: 
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get project code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Deps
        run: npm ci
      - name: Build project
        run: npm run generate
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: dist-files
      #     path: .output/public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public       
        